FROM jupyter/scipy-notebook
LABEL maintainer="Restart Us <admin@restart.us>"
ARG DOCKER_USER=jovyan
# We would use nb, but this notebook does not honor
# .bashrc or allow conda activate
ARG CONDA_ENV=base

include(../lib/lib.docker)

# https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh
add_group(sudo,$DOCKER_USER)

create_conda($CONDA_ENV,$PYTHON,$PIP,$PIP_ONLY)

set_env($DOCKER_USER,$CONDA_ENV)

WORKDIR /home/$DOCKER_USER/workspace
