#
# Makefile tuned for Python and Streamlit
#
# overriding the name
name=model
FLAGS = california --load yaml --pop dict
CA_FLAGS = california --load yaml --pop oes
MAIN = main.py

include ../lib/include.python.mk
include ../lib/include.mk
