FROM jupyter/base-notebook
LABEL maintainer="Restart Us <admin@restart.us>"
ARG DOCKER_USER=jovyan
# We would use nb, but this notebook does not honor
# .bashrc or allow conda activate
ENV CONDA_ENV=restart


include(../lib/lib.docker)
include(../lib/debug.docker)

# https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh
add_group(sudo,$DOCKER_USER)

create_conda($CONDA_ENV,$PYTHON,$PIP,$PIP_ONLY)

set_env($DOCKER_USER,$CONDA_ENV)

WORKDIR /home/$DOCKER_USER/workspace
