FROM jupyter/base-notebook
LABEL maintainer="Restart Us <admin@restart.us>"
# Using this as the base to get user working right
ARG DOCKER_USER=jovyan
ENV CONDA_ENV=restart

include(../lib/lib.docker)
include(restart.docker)

# debug tools and sudo need for conda activate
USER root
include(../lib/debug.docker)

# make a sudo user
add_group(sudo,$DOCKER_USER)

create_conda_src($CONDA_ENV)

set_env($DOCKER_USER, restart)
