
## dashboard0: first test
.PHONY: dashboard0
dashboard0:
	pipenv run streamlit run dashboard0.py

WEB = dashboard1.py

include ../../lib/include.model.mk
include ../../lib/include.python.mk
include ../../lib/include.mk
