name = model0.py

## dashboard0: first test
.PHONY: dashboard0
dashboard0:
	pipenv run streamlit dashboard0

WEB = dashboard1.py

include ../../../lib/include.python.mk
include ../../../lib/include.mk
