#
# Makefile tuned for Python and Streamlit
#
# overriding the name
#
## Airflow overall make: just run make install

include ../lib/include.airflow.mk
include ../lib/include.python.mk
include ../lib/include.mk
